version: '3.4'

services:
  srlearningserver:
    image: ${DOCKER_REGISTRY-}srlearningserver
    build:
      context: .
      dockerfile: SRLearningServer/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
